---
title: "Differentiation/UDL"
subtitle: "Tech Proficiency 5"
excerpt: "This week, the focus of EDIS 5070 was on differentiation/UDL. I decided to learn about mastery grids on my own, which are a type of differentiation."
author: "Katherine"
format: hugo
date: '2023-12-02'
slug: tech-proficiency-5
draft: false
editor_options: 
  markdown: 
    wrap: 72
---

This week, the focus of EDIS 5070 was on differentiation/UDL. I decided
to learn about mastery grids on my own, which are a type of
differentiation.

**Technology:** Mastery grid (for differentiation)

**Link to Proficiency:** [Statistics - Mastery
Grid](https://docs.google.com/document/d/1d4sIfl5kwPqcAiqj05ZDrERGuTwx6j55Ivyl_CU4pMg/edit?usp=sharing)

**Targeted Learners/Content area:** Middle school math (8th grade)

**Lesson objectives:** Learn Virginia SOL standards 8.12 and 8.13, or
how to create and analyze boxplots and scatterplots

**Lesson context:** A mastery grid is a tool that allows for self paced
student learning and differentiation. Students are free to complete the
activities in the mastery grid at their own pace following a mini lesson
at the beginning of class. During the student work time, I would aim to
conference with each student about their progress, and any
misconceptions they have. Each step of the mastery grid is targeted at
getting data on a specific checkpoint in the learning process, and each
activity serves as a formative assessment, with a summative assessment
at the end of each level. Ideal pacing would be for students to complete
one letter per day, but students can work at their own pace. All
students would need to complete through level 3 to achieve the Virginia
SOL standards. 

**Goal of technology use:** The goal of the technology use is for
students to be able to work independently at their own pace. I could in
theory modify the mastery grid for specific students who needed more or
less enrichment, but I want to have high expectations for all of my
students, and all activities available. Using technology in this way
also frees me up to conference with individual students.

**Brief description of how technology will be used with students:**
Students will have access to the mastery grid through their LMS.
Students would be expected to work independently, and flag me down if
they have any questions. Students would also fill out an accountability
form, where they would make daily and weekly goals for how much of the
mastery grid they are aiming to complete. 
