---
title: "Tech Proficiency 3"
subtitle: "Formative Assessment"
excerpt: 
author: "Katherine"
format: hugo
date: '2023-12-02'
slug: tech-proficiency-3
draft: false
editor_options: 
  markdown: 
    wrap: 72
---

**Technology:** Nearpod (used to make the quiz), R/RStudio, ggplot2
(used to make the figures for the quiz)

Link to Proficiency:
<https://app.nearpod.com/?pin=C80AEE0DE909836822E9092688F327AF-1&&utm_source=link>

<https://github.com/katherine-taylor/geometry-figures>

**Targeted Learners/Content area:** High school geometry (9-10 graders)

**Lesson objectives:** Review knowledge of coordinate transformations

**Lesson context:** This nearpod would serve as a formative assessment
for students before a mastery check on transformations. Students would
get practice with figuring out the transformation used and reviewing the
coordinate plane vocabulary.

**Goal of technology use:** The goal of the technology use is for
students to test their own knowledge of transformations on their own
time, and to provide instant feedback to the students. While these
questions could be given on paper, the questions are much clearer in
color, and the teacher cannot typically give feedback that quickly.

**Brief description of how technology will be used with students:**
Students would work individually to complete the nearpod formative
assessment. While I only included a few questions on the assessment,
there could be more questions, and students could create their own quiz
questions to test each other in nearpod. Students could also compete in
a leaderboard if I turned it on, but they might start guessing at the
answers instead of actually solving the problems.
