---
title: "Tech Proficiency 7"
subtitle: "GIS"
excerpt: 
author: "Katherine"
format: hugo
date: '2023-12-02'
slug: tech-proficiency-7
draft: false
editor_options: 
  markdown: 
    wrap: 72
---

**Technology:** GIS - r5r package in R, Github, R language, quarto
notebooks 

**Link to Proficiency:**
<https://github.com/katherine-taylor/transit-lesson>

**Targeted Learners/Content area:** Geometry (8-10th grade)

**Lesson objectives:** G.3 The student will solve problems involving
symmetry and transformation. This will include investigating and using
formulas for determining distance, midpoint, and slope (a)

**Lesson context:** Students would have previously learned about the
distance formula in their geometry class. This lesson serves to help
students understand the difference between the distance formula, and how
long it might actually take to get between two locations in the real
world. Students would also be introduced to the career opportunities of
urban planning or transportation planning, as this lesson uses real
tools both of these jobs use. Students will also create isochrone maps,
which show how far away you can get from a location in a certain amount
of time. 

**Goal of technology use:** The goal of the technology use is to have
students use R to do math, and teach them about actual models that
people use in the real world. Students would also learn about tasks that
would be challenging for them to complete by hand, and require computers
to make them easier. 

**Brief description of how technology will be used with students:**
Students would access the quarto notebook on RStudio cloud (I didn\'t
set that up for this tech proficiency since it would likely cost money),
and work through the code alongside a worksheet. I created custom
functions to abstract out some of the more complicated code, and give
custom error messages that let students know when they should get help
from me. Students would be able to work at their own pace, and play with
the code to produce different isochrone maps. If students wanted to get
deeper into the code, I included some sample analysis in R. I would
assume for this assignment that students would be introduced to RStudio
Cloud and coding in R in previous lessons. 
