---
title: "Robots"
subtitle: "Tech Proficiency 9"
excerpt: 
author: "Katherine"
format: hugo
date: '2023-12-02'
slug: tech-proficiency-9
draft: false
editor_options: 
  markdown: 
    wrap: 72
---

**Technology:** Beebots

**Link to Proficiency:** <https://www.terrapinlogo.com/beebot-ss.html>

**Targeted Learners/Content area:** Eighth grade math (grades 7-8)

**Lesson objectives:** The student will a) verify the Pythagorean
Theorem; and b) apply the Pythagorean Theorem

**Lesson context:** This lesson would serve as an introduction to the
Pythagorean theorem, and the distance formula. Students would program
beebots to outline two sides of a triangle, and then calculate how far
the bee bot traveled as the crow flies.

**Goal of technology use:** The goal of the technology use is to make
the lesson more interactive for students, and help them gain spatial
awareness of the concept. It gets old solving triangle after triangle on
paper, and the bee bots will help with problems about walking a certain
distance.

**Brief description of how technology will be used with students:**
Students will set up the bee bots to travel a specific amount left or
right, and then up or down. From there, they will measure the distance
the blue bot traveled on the diagonal, and come it to the
horizontal/vertical distances, and squared distances. Eventually, the
students will be led to understand the pythagorean theorem and how it
applies to distances.
