---
title: "Tech Proficiency 8"
subtitle: "Microbit"
excerpt: 
author: "Katherine"
format: hugo
date: '2023-12-02'
slug: tech-proficiency-8
draft: false
editor_options: 
  markdown: 
    wrap: 72
---

**Technology:** Microbits

**Link to Proficiency:** [Science Experiments 02 Population Trait
Counter](https://www.youtube.com/watch?v=NNZEMiJHY2o),
<https://katherine-taylor.github.io/sample_survey_tutorial/>

**Targeted Learners/Content area:** Middle school math (6-8)

**CS Standard:** 

7.1 The student will construct programs to accomplish a task as a means
of creative expression or scientific exploration using a block based or
text based programming language, both independently and
collaboratively, 

b\. creating clearly named variables that represent different data
types, including numeric and non-numeric data, and perform operations on
their values

**Lesson context:** This lesson would take place during a probability
and statistics unit, where students would need to collect their own
data. Students would use their microbits as data collection tools for
collecting data to analyze using mathematical tools. Students would be
required to create a program that collects data on specific topics and
outputs the data in some format. This would likely occur prior to a
summative assessment where students need to use the data they and their
classmates collected. 

**Goal of technology use:** The goal of the technology is to have
students learn how computers store information, and use algorithms to
collect data. The students will also have to learn how to write
algorithms with embedded mathematics, such as adding two categories to
get a total value. The technology also allows students to collect survey
data in a more efficient manner, and draw connections to previous
lessons on survey storage such as the Census virtual field trip.

**Brief description of how technology will be used with students:**
Students will be given an overview of the microbit, makecode, and
instructions on the assignment. Then, the students would construct their
program, using a tutorial created from the youtube video linked above.
Students would need to modify their program in one or more ways from the
tutorial. Then students would collect data from their fellow students,
and record their final data for use in further data analyses. 
