---
title: "OBS: Open Broadcaster Software"
subtitle: "Tech Proficiency 1"
excerpt: "The first week of EDIS 5070, we were tasked with creating a introductory video targeted at our future classroom. I created mine using OBS, which is an open source video software used by many video creators, and twitch streamers."
author: "Katherine"
format: hugo
date: '2023-12-02'
slug: tech-proficiency-1
draft: false
editor_options: 
  markdown: 
    wrap: 72
---

The first week of EDIS 5070, we were tasked with creating a introductory
video targeted at our future classroom. I created mine using OBS, which
is an open source video software used by many video creators, and twitch
streamers.

**Technology:** OBS

**Link to Proficiency:** [K Taylor Intro
Video](https://drive.google.com/file/d/1twUCK8UsDw13bX5lGpt9d1eOyKSryRsP/view?usp=sharing)

**Targeted Learners/Content area:** Middle School Pre-Algebra

**Lesson objectives:** Give students a short introduction to their class
and their instructor

**Lesson context:** This video would be posted on canvas on another LMS
for students to watch at the beginning of the school year. Students
would ideally watch this video before the first day of class to get to
know me prior to the start, but also might watch the video for homework
during the first few days of class.

**Goal of technology use:** I believe that creating an introduction
video will allow students to get to know me a little before class
starts. It would also allow me to spend more time in class getting to
know the students and less time on introducing myself. I also want the
video to get students to start thinking critically about essential
questions that will be covered in my class.

**Brief description of how technology will be used with students:** The
video I create is fairly teacher centric, but I foresee students needing
to create videos to present their own work as well. Students could also
make introductory videos to get more comfortable with using video
creation software, so when they create videos about content later in the
school year, they would be better prepared.
